export const CATEGORY_ACTION_TYPES = {
  // SET_CURRENT_SHOP: 'SET_CURRENT_SHOP',
  // thunk
  FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILED: 'FETCH_CATEGORIES_FAILED'
}
