export const CART_ACTION_TYPES = {
  SET_CART_COUNT: 'SET_CART_COUNT',
  SET_CART_TOTAL_PRICE: 'SET_CART_TOTAL_PRICE',
  SET_CART_ITEM: 'SET_CART_ITEM',
  SET_CART_DROPDOWN: 'SET_CART_DROPDOWN',
}
